apiVersion: flink.apache.org/v1beta1

kind: FlinkDeployment

metadata:

  name: flink-job

spec:

  image: notwarrier/flinkjob:latest

  imagePullPolicy: Always

  flinkVersion: v1_17

  flinkConfiguration:

    taskmanager.numberOfTaskSlots: "2"

  serviceAccount: flink

  jobManager:

    resource:

      memory: "2048m"

      cpu: 1

  taskManager:

    resource:

      memory: "2048m"

      cpu: 1

  job:

    jarURI: local:///opt/flink/usrlib/flink-example-1.0-SNAPSHOT.jar

    parallelism: 2

    upgradeMode: stateless

    state: running